### ISSUE TITLE
Better search functionality

### ISSUE THREAD

**Issue by thdaele** [OrnitheMC/enigma#2]
- [ ] Fix crashes/freezes when using the search function

**Comment by viktor40** [comment]
- [ ] Create a search window with 3 tabs:
       - Search Classes
       - Search Methods
       - Search Fields
- [ ] Change search keybind to `ctrl + shift + F`

**Comment by viktor40** [comment]
I think all of these issues might now be solved? The crashes don't occur anymore in the new enigma version for me. I think we can close this issue then?

**Comment by thdaele** [comment]
Yeah I can't seem to replicate with quilt fork either
