### ISSUE TITLE
Check mappings against the style guide

### ISSUE THREAD

**Issue by thdaele** [OrnitheMC/enigma#4]
- [x] check mapped names against the style guide

**Comment by viktor40** [comment]
As per #9 the `Static Final` fields are checked against the style guide. Which other parts of the style guide do we want to check in enigma?

**Comment by SpaceWalkerRS** [comment]
> Which other parts of the style guide do we want to check in enigma?

Most points in the style guide are naming conventions, which makes checking against them rather difficult, I imagine (not least because some of them depend on the very mappings we use).

**Comment by viktor40** [comment]
Personally I think there might be some easy things we can add. For example if we decide on a set of abbreviations to use or not to use. For example if you use `minimum` instead of min. That would be easy to check. But that would maybe be something we can discuss after the revised style guide is finished.

**Comment by thdaele** [comment]
Well we can easily check if a class starts with a capital letter. Same for methods and fields those have to start with a regular letter.

**Comment by viktor40** [comment]
that should be implemented now

**Comment by viktor40** [comment]
This issue got accidentally closed when merging #9 . I hereby reopen this issue for further mapping checks that will come when we finished the new style guide.

**Comment by viktor40** [comment]
This issue got accidentally closed when merging #9 . I hereby reopen this issue for further mapping checks that will come when we finished the new style guide.
