### ISSUE TITLE
Fix javadocs

### ISSUE THREAD

**Issue by thdaele** [OrnitheMC/enigma#6]
- [x] Properly render them
- [ ] Javadoc doesn't change function param name when the function param name gets changed. Workaround for this atm is: edit javadoc, save and it will update it.

**Comment by viktor40** [comment]
Render javadocs as tooltips.

**Comment by viktor40** [comment]
As of #26 javadoc rendering is implemented

**Comment by viktor40** [comment]
Can you elaborate on the second part of this issue? I don't quite understand what you mean.

**Comment by viktor40** [comment]
The second part of this pr will not be fixed yet and will be implemented as a seperate feature. I will close this issue when merging #26 and create seperate issues for future features for the javadocs.
